### PR TITLE
Revert "In case path contains spaces"

### PR DESCRIPTION
**Pull request by Babuh**
This reverts commit 99a90821f9facf506e5f9bab8d8cd05c470be5ad.
This revert is here to fixe the contributor add failure.
The changes of commit 99a90821f9facf506e5f9bab8d8cd05c470be5ad will be added once again just after.

### CODE REVIEW

**Comment by DanRumery** [comment]
Hi @Babuh 

I've merged the pull request with the revert but I noticed that I still can't click your name in the commit list which suggests to me that Github is still not associating the commit author with your profile for some reason...

I'm reading this: [Why are my contributions not showing up on my profile?](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/)

but I don't see anything obviously wrong. Let's wait 24 hours and see if it fixes itself. Then try re-adding your original commit.

**Comment by DanRumery** [comment]
Possibly see also: [Why are my commits linked to the wrong user?](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/)

**Comment by Babuh** [comment]
The second bullet point say : "The commits were made in a standalone repository, not a fork."
At first I wanted to create a branch but it seems like I can't, so in order to add my pull request I forked your repo. I guess that is why you can't see me in the contributors tab (the second contributor in the contributor tab had his pull request from a branch). 
Maybe you have to create an alternative branch and give me rights to commit on it. 
Sorry I'm not very familiar to Github, we use GitLab at work ^^

**Comment by DanRumery** [comment]
Yes I think you're right.  I'll probably have to add you as an "outside" collaborator and give you push permissions. Let me see...

**Comment by DanRumery** [comment]
@Babuh   Hey I've just noticed that your commit email address still doesn't match the one you have in your GitHub profile. This is the source of the problem!

Indeed if users couldn't contribute via pull requests from fork then the whole contributor system would be broken :)

**Pull request merged**
